name: HEX

settings:
  DEVELOPMENT_TEAM: K78G42H4U2
  CURRENT_PROJECT_VERSION: 19
  MARKETING_VERSION: 0.1.0

options:
  bundleIdPrefix: com.joeblau
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
  preGenCommand: .github/scripts/pre.sh
  postGenCommand: .github/scripts/post.sh

packages:
  swift-composable-architecture:
    url: https://github.com/pointfreeco/swift-composable-architecture.git
    from: 0.17.0
  swift-identified-collections:
    url: https://github.com/pointfreeco/swift-identified-collections.git
    from: 0.3.0
  swiftui-visual-effects:
    url: https://github.com/lucasbrown/swiftui-visual-effects.git
    from: 1.0.3
  lightweight-charts:
    url: https://github.com/tradingview/LightweightChartsIOS.git
    from: 3.6.1

localPackages:
  - ./Packages/hex-smart-contract/
  - ./Packages/hex-rest/
  - ./Packages/bitquery-api/

targets:
  HEX:
    type: application
    platform: iOS
    sources:
      - path: Apps/HEX
        excludes:
          - Apps/HEX/PreviewContent/*
      - path: Apps/HEX/Resources/
        buildPhase: resources
    settings:
      OTHER_LDFLAGS: -ObjC
      DEVELOPMENT_ASSET_PATHS: Apps/HEX/PreviewContent
      PRODUCT_BUNDLE_IDENTIFIER: com.joeblau.HEX
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      TARGETED_DEVICE_FAMILY: 1
      VALIDATE_WORKSPACE: true
    dependencies:
      - package: hex-smart-contract
        product: HEXSmartContract
      - package: hex-rest
        product: HEXREST
      - package: bitquery-api
        product: BitqueryAPI
      - package: lightweight-charts
        product: LightweightCharts
      - package: swift-composable-architecture
        product: ComposableArchitecture
      - package: swift-identified-collections
        product: IdentifiedCollections
      - package: swiftui-visual-effects
        product: SwiftUIVisualEffects
